//! Validation half of the C ABI — every `export fn` a consumer needs to
//! answer "is this file OK, and if not, why?", and nothing else.
//!
//! This file is the root of `libjpegz-validate.a` and is ALSO force-linked
//! into the full `libjpegz.a`, so the two libraries agree symbol-for-symbol on
//! the validation surface. The decode entry points live in `c_api.zig`.
//!
//! The separation is load-bearing, not tidiness: every declaration reachable
//! from here must be pure Zig (plus Brotli, which libjxlz uses to read JXL
//! container metadata). Referencing anything that reaches
//! `openjpeg_wrapper` / `libjpeg_wrapper` / `charls_wrapper` would drag those
//! C libraries back into the validation closure, and the Nix
//! `validator-closure` check exists to catch exactly that. See
//! `c_common.zig`'s header for why the archive split is required at all.

const std = @import("std");
const errors = @import("../core/errors.zig");
const jpegz = @import("../jpegz.zig");
const common = @import("c_common.zig");

const c_allocator = common.c_allocator;
const clearLastError = common.clearLastError;
const setLastError = common.setLastError;
const toCStatus = common.toCStatus;
const OFFSET_NONE = common.OFFSET_NONE;
const CFinding = common.CFinding;
const CValidationReport = common.CValidationReport;

// ─────────────────────────────────────────────────────────────────────
// Identity / diagnostics — needed by BOTH libraries, so they live on the
// validation side (which the full library always includes).
// ─────────────────────────────────────────────────────────────────────

export fn jpegz_last_error_message() [*:0]const u8 {
    return common.last_error.cPtr();
}

export fn jpegz_version() [*:0]const u8 {
    return jpegz.version.ptr;
}

/// Human-readable name for a `jpegz_finding_code_t`, e.g. 3 →
/// `"truncated_stream"`. Statically allocated; the caller must NOT free it.
///
/// Exists so consumers report a *specific cause* rather than a bare integer.
/// Without it every consumer that renders findings would hand-maintain its own
/// code→name table, which silently drifts from `core/errors.zig` the moment a
/// code is appended — and appending is routine, since the registry is
/// append-only wire format.
///
/// Generated by `inline for` over `@typeInfo(...).fields`, so drift is not
/// merely discouraged but inexpressible: a new `FindingCode` variant is
/// nameable the instant it is declared, with no second edit site.
///
/// Unknown codes return `"unknown_finding_code"` rather than null or garbage.
/// That case is reachable in normal operation, not just from misuse: findings
/// cross an ABI boundary, so a newer jpegz can hand an older consumer a code
/// it predates.
export fn jpegz_finding_code_name(code: c_int) [*:0]const u8 {
    inline for (@typeInfo(errors.FindingCode).@"enum".fields) |f| {
        if (code == f.value) return f.name.ptr;
    }
    return "unknown_finding_code";
}

// ─────────────────────────────────────────────────────────────────────
// Severity-rated report (the original validation ABI)
// ─────────────────────────────────────────────────────────────────────

export fn jpegz_validation_report_free(report: ?*CValidationReport) void {
    const r = report orelse return;
    common.freeCFindings(r.findings, r.findings_len);
    r.* = std.mem.zeroes(CValidationReport);
}

fn doValidate(
    validator: *const fn (std.mem.Allocator, []const u8) error{OutOfMemory}!jpegz.ValidationReport,
    data: [*c]const u8,
    len: usize,
    out_report: ?*CValidationReport,
) c_int {
    clearLastError();
    const out = out_report orelse {
        setLastError("out_report must not be NULL", .{});
        return -8; // OUT_OF_MEMORY-adjacent; reuse for invalid-arg-NULL.
    };
    const slice: []const u8 = if (data == null or len == 0) &[_]u8{} else data[0..len];
    var report = validator(c_allocator, slice) catch |err| {
        setLastError("validate failed: {s}", .{@errorName(err)});
        return toCStatus(err);
    };
    defer report.deinit(c_allocator);

    const c_findings = common.buildCFindings(report.findings.items) catch {
        setLastError("OOM building C findings", .{});
        return -8;
    };

    out.* = .{
        .overall = @intFromEnum(report.overall),
        .variant = @intFromEnum(report.variant),
        .width = report.width orelse 0,
        .height = report.height orelse 0,
        .findings = c_findings,
        .findings_len = report.findings.items.len,
    };
    return 0;
}

export fn jpegz_validate(data: [*c]const u8, len: usize, out_report: ?*CValidationReport) c_int {
    return doValidate(jpegz.validate, data, len, out_report);
}

export fn jpegz_jp2_validate(data: [*c]const u8, len: usize, out_report: ?*CValidationReport) c_int {
    return doValidate(jpegz.jpeg2000.validate, data, len, out_report);
}

// ─────────────────────────────────────────────────────────────────────
// Strict JPEG-family facade
// ─────────────────────────────────────────────────────────────────────
//
// Mirrors `jpegz.validateAny`. The four-way verdict and the leaf's raw code
// both cross the ABI intact: a C consumer must be able to distinguish "clean",
// "damaged", "I don't cover this feature" and "I could not tell", and to log
// the originating validator's own code when jpegz has no name for it.

const FINDING_UNMAPPED: c_int = -1;

const CStrictFinding = extern struct {
    source: c_int,
    leaf_code: u32,
    code: c_int,
    severity: c_int,
    offset: i64,
    host_offset: i64,
    offset_is_exact: c_int,
    detail: ?[*:0]const u8,
};

const CStrictResult = extern struct {
    verdict: c_int,
    format: c_int,
    variant: c_int,
    width: u32,
    height: u32,
    frames_validated: u32,
    findings: [*c]const CStrictFinding,
    findings_len: usize,
};

fn buildCStrictFindings(zig_findings: []const jpegz.facade.StrictFinding) ![*c]CStrictFinding {
    if (zig_findings.len == 0) return null;
    const arr = try c_allocator.alloc(CStrictFinding, zig_findings.len);
    errdefer c_allocator.free(arr);

    for (zig_findings, 0..) |f, i| {
        arr[i] = .{
            .source = @intFromEnum(f.source),
            .leaf_code = f.leaf_code,
            .code = if (f.code) |c| @intCast(@intFromEnum(c)) else FINDING_UNMAPPED,
            .severity = @intFromEnum(f.severity),
            .offset = if (f.offset) |o| @intCast(o) else OFFSET_NONE,
            .host_offset = if (f.host_offset) |o| @intCast(o) else OFFSET_NONE,
            .offset_is_exact = @intFromBool(f.offset_is_exact),
            .detail = try common.dupeDetailToC(f.detail),
        };
    }
    return @ptrCast(arr.ptr);
}

export fn jpegz_strict_result_free(result: ?*CStrictResult) void {
    const r = result orelse return;
    if (r.findings != null and r.findings_len != 0) {
        var i: usize = 0;
        while (i < r.findings_len) : (i += 1) {
            if (r.findings[i].detail) |d| common.freeDetailFromC(d);
        }
        const arr = @as([*]CStrictFinding, @constCast(@ptrCast(r.findings)))[0..r.findings_len];
        c_allocator.free(arr);
    }
    r.* = std.mem.zeroes(CStrictResult);
}

export fn jpegz_sniff(data: [*c]const u8, len: usize) c_int {
    const slice: []const u8 = if (data == null or len == 0) &[_]u8{} else data[0..len];
    return @intFromEnum(jpegz.sniff(slice));
}

export fn jpegz_validate_any(data: [*c]const u8, len: usize, out_result: ?*CStrictResult) c_int {
    clearLastError();
    const out = out_result orelse {
        setLastError("out_result must not be NULL", .{});
        return -8;
    };
    const slice: []const u8 = if (data == null or len == 0) &[_]u8{} else data[0..len];
    var result = jpegz.validateAny(c_allocator, slice) catch |err| {
        setLastError("validateAny failed: {s}", .{@errorName(err)});
        return toCStatus(err);
    };
    defer result.deinit(c_allocator);

    const c_findings = buildCStrictFindings(result.findings.items) catch {
        setLastError("OOM building C strict findings", .{});
        return -8;
    };

    out.* = .{
        .verdict = @intFromEnum(result.verdict),
        .format = @intFromEnum(result.format),
        .variant = @intFromEnum(result.variant),
        .width = result.width orelse 0,
        .height = result.height orelse 0,
        .frames_validated = result.frames_validated,
        .findings = c_findings,
        .findings_len = result.findings.items.len,
    };
    return 0;
}

export fn jpegz_verdict_name(verdict: c_int) [*:0]const u8 {
    inline for (@typeInfo(jpegz.StrictVerdict).@"enum".fields) |f| {
        if (verdict == f.value) return f.name.ptr;
    }
    return "unknown_verdict";
}

export fn jpegz_validation_format_name(format: c_int) [*:0]const u8 {
    inline for (@typeInfo(jpegz.ValidationFormat).@"enum".fields) |f| {
        if (format == f.value) return f.name.ptr;
    }
    return "unknown_format";
}
